### ISSUE TITLE
[non-python2.7 OS][Debian 6 x64/x86] install failed with dpkg error

### ISSUE THREAD

**Issue by Wayenyin** [Microsoft/omi-script-provider#39] opened 2017-10-17 07:38 UTC
**ENV**

-   Clients: 
omi86-deb6-t3 [10.226.138.148]         
omi64-deb6-t3 [10.226.198.21]

**Build**

- omi build 1.4.0-2: [\\\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.0-2\Linux_ULINUX_1.0_x64_64_Release\openssl_0.9.8 
](\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.0-2\Linux_ULINUX_1.0_x64_64_Release\openssl_0.9.8 )
- Python script provider: [\\\\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-10  ](\\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-10)

**Repro Steps**

1. Install omi package version 1.4.0-2;
2. Check omi process and package;
    ```
    root@omi64-deb6-t3  # ps -ef|grep omi
    root      1690     1  0 17:12 ?        00:00:00 /opt/omi/bin/omiserver --configfile=/etc/opt/omi/conf/omiserver.conf -d
    omi       1691  1690  0 17:12 ?        00:00:00 /opt/omi/bin/omiengine --configfile=/etc/opt/omi/conf/omiserver.conf -d --logfilefd 3 --socketpair 9
    root      1725  1500  0 17:15 pts/0    00:00:00 grep omi
    
    ~
    root@omi64-deb6-t3  # dpkg -l|grep omi
    ii  omi                                 1.4.0.2                      Open Management Infrastructure

    ~
    ```
3. Install Python script provider but failed: [\\\\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-10 ](\\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-10 )
    ```
    root@omi64-deb6-t3  # dpkg -i OMIScriptProvider-1.1.1-10.x64.deb 
    Selecting previously deselected package omiscriptprovider.
    (Reading database ... 22784 files and directories currently installed.)
    Unpacking omiscriptprovider (from OMIScriptProvider-1.1.1-10.x64.deb) ...
    dpkg (subprocess): unable to execute new pre-installation script (/var/lib/dpkg/tmp.ci/preinst): Exec format error
    dpkg: error processing OMIScriptProvider-1.1.1-10.x64.deb (--install):
    subprocess new pre-installation script returned error exit status 2
    dpkg (subprocess): unable to execute new post-removal script (/var/lib/dpkg/tmp.ci/postrm): Exec format error
    dpkg: error while cleaning up:
    subprocess new post-removal script returned error exit status 2
    Errors were encountered while processing:
    OMIScriptProvider-1.1.1-10.x64.deb
    
    ~
    ```

4. Check omi process but failed:
    ```
    root@omi64-deb6-t3  # dpkg -l|grep omiscriptprovider
    iHR omiscriptprovider                   1.1.1.10                     (no description available)
    
    ~
    ```

**Expectly:** Python script provider package should be installed successfully.
**Actual:**  Installed script provider failed.

**Comment by JumpingYang001** [comment] 2017-10-17 07:55
We didn't find this yesterday, sorry for this, we were using tool to run and the tool show it is installed... in fact it is always exist. the earliest python build is 1.1.1-5 it is built on 10/09/2017(last week).
we find this issue today, we are busying testing omi yesterday so lose this python issue but we find it today. 
BTW, deb6's default python is not python2.7.

**Comment by JumpingYang001** [comment] 2017-10-18 05:44
support python2.7 OS first, so change P0 to P2

**Comment by JumpingYang001** [comment] 2017-10-19 08:55
Changed from P2 to P3 since this platform aren't in this time's release, we only support python2.7 in this release.

**Comment by alinbalutoiu** [comment] 2017-10-26 09:32
Closing this issue since it's a duplicate of issue #43

**Comment by JumpingYang001** [comment] 2017-10-26 09:53
@alinbalutoiu  this issue is installation issue, but #43 is omireg issue. different.

**Comment by alinbalutoiu** [comment] 2017-10-26 10:23
@JumpingYang001 how could you run "omireg --Python" without installing the package on Debian 6 then?

**Comment by JumpingYang001** [comment] 2017-10-26 13:09
@alinbalutoiu , you are right, I will check this issue tomorrow, thanks.

**Comment by JumpingYang001** [comment] 2017-10-27 03:06
@alinbalutoiu , I have removed Debian 6 (x64/x86) in #43 , they are different issue, this is an installation issue, so re-open this issue, thanks.

**Comment by alinbalutoiu** [comment] 2017-10-27 09:09
Are you sure on the rest of the systems there is not the same issue? You haven't introduced any hacks like create a symlink named python2.7 for python 2.6? The installation package uses explicitly the python2.7 command. If you created a symlink and got the omireg that should be mentioned at least in the issue description in my opinion.

**Comment by JumpingYang001** [comment] 2017-10-27 09:38
Yup, it is another installation error, I have updated another issue, there are all installation issue, but errors are different.

**Comment by JumpingYang001** [comment] 2017-10-27 09:45
For P3 issues, we can do it in next release, or if these is no customer request support it then we needn't do it, thanks.

**Comment by JumpingYang001** [comment] 2017-10-27 09:46
For this time's release, we only care P0 and P1 issues, thank you!

**Comment by JumpingYang001** [comment] 2017-10-27 09:48
Just close this, and if we need to support non-python2.7 in the future, then we can test them that time.

**Closed as completed by JumpingYang001** 2017-10-27 09:48 UTC
Labels: P3
